name: gasta_user_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.60.3
  gasta_core: 
    path: ../Core/
  http: ^1.1.0
  qr_code_scanner: ^1.0.1
  flutter_launcher_icons: ^0.12.0
  shared_preferences: ^2.2.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
